// <auto-generated />
using System;
using Locatic.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Locatic.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LocaticDbContext))]
    [Migration("20260628122131_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Locatic.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "lucas.martin@example.com",
                            Nom = "Martin",
                            Prenom = "Lucas",
                            Telephone = "0601020304"
                        },
                        new
                        {
                            Id = 2,
                            Email = "emma.bernard@example.com",
                            Nom = "Bernard",
                            Prenom = "Emma",
                            Telephone = "0605060708"
                        });
                });

            modelBuilder.Entity("Locatic.Domain.Entities.Marque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaysOrigine")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Marques");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Renault",
                            PaysOrigine = "France"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Peugeot",
                            PaysOrigine = "France"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "BMW",
                            PaysOrigine = "Allemagne"
                        });
                });

            modelBuilder.Entity("Locatic.Domain.Entities.Modele", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarqueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarqueId");

                    b.ToTable("Modeles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MarqueId = 1,
                            Nom = "Clio"
                        },
                        new
                        {
                            Id = 2,
                            MarqueId = 1,
                            Nom = "Captur"
                        },
                        new
                        {
                            Id = 3,
                            MarqueId = 2,
                            Nom = "208"
                        },
                        new
                        {
                            Id = 4,
                            MarqueId = 2,
                            Nom = "308"
                        },
                        new
                        {
                            Id = 5,
                            MarqueId = 3,
                            Nom = "Série 3"
                        },
                        new
                        {
                            Id = 6,
                            MarqueId = 3,
                            Nom = "X1"
                        });
                });

            modelBuilder.Entity("Locatic.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateFin")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VoitureId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("VoitureId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            DateDebut = new DateOnly(2026, 7, 1),
                            DateFin = new DateOnly(2026, 7, 5),
                            Montant = 159.60m,
                            VoitureId = 1
                        });
                });

            modelBuilder.Entity("Locatic.Domain.Entities.Voiture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Annee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Carburant")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Immatriculation")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int>("ModeleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NombrePlaces")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TarifJournalier")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Immatriculation")
                        .IsUnique();

                    b.HasIndex("ModeleId");

                    b.ToTable("Voitures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Annee = 2021,
                            Carburant = "Essence",
                            Immatriculation = "AA-123-BB",
                            ModeleId = 1,
                            NombrePlaces = 5,
                            TarifJournalier = 39.90m
                        },
                        new
                        {
                            Id = 2,
                            Annee = 2022,
                            Carburant = "Diesel",
                            Immatriculation = "CD-456-EF",
                            ModeleId = 2,
                            NombrePlaces = 5,
                            TarifJournalier = 45.00m
                        },
                        new
                        {
                            Id = 3,
                            Annee = 2023,
                            Carburant = "Hybride",
                            Immatriculation = "GH-789-IJ",
                            ModeleId = 3,
                            NombrePlaces = 5,
                            TarifJournalier = 52.50m
                        },
                        new
                        {
                            Id = 4,
                            Annee = 2020,
                            Carburant = "Essence",
                            Immatriculation = "KL-012-MN",
                            ModeleId = 5,
                            NombrePlaces = 5,
                            TarifJournalier = 75.00m
                        },
                        new
                        {
                            Id = 5,
                            Annee = 2024,
                            Carburant = "Electrique",
                            Immatriculation = "OP-345-QR",
                            ModeleId = 6,
                            NombrePlaces = 5,
                            TarifJournalier = 89.00m
                        });
                });

            modelBuilder.Entity("Locatic.Domain.Entities.Modele", b =>
                {
                    b.HasOne("Locatic.Domain.Entities.Marque", "Marque")
                        .WithMany("Modeles")
                        .HasForeignKey("MarqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marque");
                });

            modelBuilder.Entity("Locatic.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("Locatic.Domain.Entities.Client", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Locatic.Domain.Entities.Voiture", "Voiture")
                        .WithMany("Reservations")
                        .HasForeignKey("VoitureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Voiture");
                });

            modelBuilder.Entity("Locatic.Domain.Entities.Voiture", b =>
                {
                    b.HasOne("Locatic.Domain.Entities.Modele", "Modele")
                        .WithMany("Voitures")
                        .HasForeignKey("ModeleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modele");
                });

            modelBuilder.Entity("Locatic.Domain.Entities.Client", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Locatic.Domain.Entities.Marque", b =>
                {
                    b.Navigation("Modeles");
                });

            modelBuilder.Entity("Locatic.Domain.Entities.Modele", b =>
                {
                    b.Navigation("Voitures");
                });

            modelBuilder.Entity("Locatic.Domain.Entities.Voiture", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
