apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: locatic
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: locatic
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: alertmanager
  ports:
    - name: http
      port: 9093
      targetPort: http
